# Generated by Django 2.2 on 2023-09-15 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushups.WorkoutType'),
        ),
        migrations.AlterField(
            model_name='benchmarktest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 16, 51, 35, 219097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 16, 51, 35, 219348, tzinfo=utc)),
        ),
    ]
