# Generated by Django 2.2 on 2023-09-15 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushups', '0002_auto_20230915_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='total_pushups',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='benchmarktest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 18, 29, 56, 643274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 18, 29, 56, 643523, tzinfo=utc)),
        ),
    ]
