# Generated by Django 2.2 on 2023-09-15 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushups', '0007_auto_20230915_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarktest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 21, 25, 42, 232946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 21, 25, 42, 233188, tzinfo=utc)),
        ),
    ]
